<?php
/**
 *
 *
 */
?>
<script>
    var EDIPOST_OPEN_EDIPOST_AJAX_URL = '<?php /* @escapeNotVerified */ echo ($block->getAjaxUrl())['open']; ?>',
        EDIPOST_CREATE_SHIPMENT_AJAX_URL = '<?php /* @escapeNotVerified */ echo ($block->getAjaxUrl())['create']; ?>',
        EDIPOST_ORDER_ID = <?php /* @escapeNotVerified */ echo $block->getIdOrder() ?>,
        EDIPOST_PRINTER = '<?php /* @escapeNotVerified */ echo ($block->getPrinterData())['printer'] ?>',
        EDIPOST_PRINTER_RFID = '<?php /* @escapeNotVerified */ echo ($block->getPrinterData())['printer_rfid'] ?>';

    require([
        'Edipost_Shipment/js/edipost'
    ]);

</script>