<?php
if (!$block->isModuleEnable()) {
    return;
}
?>
<section class="admin__page-section edipost-wrapper">
    <?php $shippingMethods = $block->getShippingMethods(); ?>

    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */
            __('Edipost integration') ?></span>
    </div>

    <?php if ($sError = $shippingMethods->error) { ?>
        <label class="mage-error" style="margin-bottom: 20px;"><?= $sError ?></label>
    <?php } ?>

    <div class="" id="error-block" style="display: none">
        <div class="messages"></div>
    </div>

    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-edipost-shipments">
            <div id="order_edipost_block" class="edit-shipments">
                <div class="edipost-block" id="edipost_form">

                    <div class="admin__field">
                        <label for="edipost_ship_method" class="admin__field-label"><?= /* @escapeNotVerified */
                            __('Choose shipping method') ?></label>
                        <div class="admin__field-control">
                            <select name="edipost[ship_method]" id="edipost_ship_method" class="admin__control-select">
                                <?php foreach ($shippingMethods->options as $option) { ?>
                                    <option <?= ($option['status'] == 'Available') ? '' : 'disabled title="' . $option['status'] . '"' ?> value="<?= $option['id'] ?>" data-service="<?= $option['service'] ?>"><?= $option['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="admin__field">
                        <label for="edipost_reference" class="admin__field-label"><?= /* @escapeNotVerified */
                            __('Reference text (optional)') ?></label>
                        <div class="admin__field-control">
                            <textarea name="edipost[reference]" style="width: 313px; height: 60px;" id="edipost_reference" class="admin__control-textarea"></textarea>
                        </div>
                    </div>

                    <div class="admin__field">
                        <div class="edipost-e-allert-options">
                            <div class="admin__field admin__field-option">
                                <input type="checkbox" name="edipost[e_alert]" id="edipost_e_alert" class="admin__control-checkbox" checked>
                                <label for="edipost_e_alert" class="admin__field-label"><?= /* @escapeNotVerified */
                                    __('Electronic alert on SMS/Email') ?></label>
                            </div>
                        </div>
                    </div>

                    <div class="admin__field">

                        <div class="order-edipost-shipments-actions">
                            <button id="edipost-create" title="Create shipment" type="button"
                                    class="action-default scalable action-save action-secondary"
                                    data-ui-id="widget-button-0">
                                <span><?= /* @escapeNotVerified */
                                    __('Create shipment') ?></span>
                            </button>
                            <button <?= $block->isConfigEmpty() ? 'disabled' : '' ?> id="edipost-open"
                                                                                     title="Open in Edipost"
                                                                                     type="button"
                                                                                     class="action-default scalable action-save action-secondary"
                                                                                     data-ui-id="widget-button-1">
                                <span><?= /* @escapeNotVerified */
                                    __('Open in Edipost') ?></span>
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</section>
