<?php
if (!$block->isModuleEnable()) {
    return;
}
?>
<section class="admin__page-section edipost-wrapper">
    <?php $shipingMethods = $block->getShipingMethods(); ?>

    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */
            __('Edipost integration') ?></span>
    </div>

    <?php if ($sError = $shipingMethods->error) { ?>
        <label class="mage-error" style="margin-bottom: 20px;"><?= $sError ?></label>
    <?php } ?>

    <div class="admin__page-section-title" id="error-block" style="display: none">
        <div id="debug" style="width: 650px; height: 300px; border: 1px solid black; overflow: scroll;"></div>
    </div>

    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-edipost-shipments">
            <div id="order_edipost_block" class="edit-shipments">
                <div class="edipost-block" id="edipost_form">

                    <div class="admin__field">
                        <label for="edipost_ship_method" class="admin__field-label"><?= /* @escapeNotVerified */
                            __('Chose shipping method') ?></label>
                        <div class="admin__field-control">
                            <select name="edipost[ship_method]" id="edipost_ship_method" class="admin__control-select">
                                <?php foreach ($shipingMethods->options as $option) { ?>
                                    <option <?= ($option['status'] == 'Available') ? '' : 'disabled title="' . $option['status'] . '"' ?>
                                            value="<?= $option['id'] ?>"><?= $option['name'] ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>

                    <div class="admin__field">
                        <label for="edipost_reference" class="admin__field-label"><?= /* @escapeNotVerified */
                            __('Reference text(optional)') ?></label>
                        <div class="admin__field-control">
                            <textarea name="edipost[reference]" rows="3" cols="5" id="edipost_reference"
                                      class="admin__control-textarea"></textarea>
                        </div>
                    </div>

                    <div class="admin__field">
                        <label for="edipost_e_alert" class="admin__field-label"><?= /* @escapeNotVerified */
                            __('Electronic alert on SMS/Email') ?></label>
                        <div class="admin__field-control">
                            <checkbox name="edipost[e_alert]"  id="edipost_e_alert"
                                      class="admin__control-checkbox"></checkbox>
                        </div>
                    </div>

                    <div class="admin__field">

                        <div class="order-edipost-shipments-actions">
                            <button id="edipost-create" title="Create shipment" type="button"
                                    class="action-default scalable action-save action-secondary"
                                    data-ui-id="widget-button-0">
                                <span><?= /* @escapeNotVerified */
                                    __('Create shipment') ?></span>
                            </button>
                            <button <?= $block->isConfigEmpty() ? 'disabled' : '' ?> id="edipost-open"
                                                                                     title="Open in Edipost"
                                                                                     type="button"
                                                                                     class="action-default scalable action-save action-secondary"
                                                                                     data-ui-id="widget-button-1">
                                <span><?= /* @escapeNotVerified */
                                    __('Open in Edipost') ?></span>
                            </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</section>
