<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Edipost integration') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-edipost-shipments">
            <div id="order_edipost_block" class="edit-shipments">
                <div class="edipost-block" id="edipost_form">

                    <div class="admin__field">
                        <label for="edipost_ship_method" class="admin__field-label"><?= /* @escapeNotVerified */ __('Chose shipping method') ?></label>
                        <div class="admin__field-control">
                            <select name="edipost[ship_method]" id="edipost_ship_method" class="admin__control-select">
                                <option value="test1">test1</option>
                                <option value="test2">test2</option>
                                <option value="test3">test3</option>
                            </select>
                        </div>
                    </div>

                    <div class="admin__field">
                        <label for="edipost_reference" class="admin__field-label"><?= /* @escapeNotVerified */ __('Reference text(optional)') ?></label>
                        <div class="admin__field-control">
                            <textarea name="edipost[reference]" rows="3" cols="5" id="edipost_reference" class="admin__control-textarea"></textarea>
                        </div>
                    </div>

                    <div class="admin__field">

                        <div class="order-edipost-shipments-actions">
                            <button id="some_id1" title="Create shipment" type="button" class="action-default scalable action-save action-secondary" data-ui-id="widget-button-0">
                                <span><?= /* @escapeNotVerified */ __('Create shipment') ?></span>
                            </button>
                            <button id="some_id2" title="Open in Edipost" type="button" class="action-default scalable action-save action-secondary" data-ui-id="widget-button-1">
                                <span><?= /* @escapeNotVerified */ __('Open in Edipost') ?></span>
                            </button>
                        </div>
                    </div>
                </div>


            </div>
        </div>

    </div>
</section>